package Konami.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import ArduinoML.textGen.Component;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import java.util.List;

public class KonamiComposant_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    Component.init_component(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), node, "virtual_getPins_4453370684997361065", new Object[]{}), "INPUT", this);
  }
}
