package Konami.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class KonamiComposant_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public KonamiComposant_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Konami.structure.KonamiComposant";
  }
}
