package Konami.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StateProxy_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StateProxy_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Konami.structure.StateProxy";
  }
}
