package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class AbstractRule_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AbstractRule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.AbstractRule";
  }
}
