package ArduinoML.behavior;

/*Generated by MPS */


public class ActionCallModule_BehaviorDescriptor extends AbstractAction_BehaviorDescriptor {
  public ActionCallModule_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ActionCallModule";
  }
}
