package ArduinoML.behavior;

/*Generated by MPS */


public class ActionOnComponent_BehaviorDescriptor extends AbstractAction_BehaviorDescriptor {
  public ActionOnComponent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ActionOnComponent";
  }
}
