package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class AnalogicIN_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getType_4453370684997412076(SNode thisNode) {
    return "analog";
  }

  public static String virtual_expectedValue_66643460712565918(SNode thisNode, String state) {
    if (state.equals("HIGH")) {
      return "> THRESHOLD_HIGH";
    } else {
      return "< THRESHOLD_LOW";
    }
  }
}
