package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class ArduinoML_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.addNewChild(thisNode, "modules", "ArduinoML.structure.Module");
    SPropertyOperations.set(ListSequence.fromList(SLinkOperations.getTargets(thisNode, "modules", true)).first(), "name", "mainly");

  }
}
