package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 4:
        return new Program_BehaviorDescriptor();
      case 3:
        return new DecisionTable_BehaviorDescriptor();
      case 0:
        return new Action_BehaviorDescriptor();
      case 1:
        return new Component_BehaviorDescriptor();
      case 5:
        return new Status_BehaviorDescriptor();
      case 2:
        return new Decision_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"ArduinoML.structure.Action", "ArduinoML.structure.Component", "ArduinoML.structure.Decision", "ArduinoML.structure.DecisionTable", "ArduinoML.structure.Program", "ArduinoML.structure.Status"};
}
