package ArduinoML.behavior;

/*Generated by MPS */


public class Break_BehaviorDescriptor extends AbstractAction_BehaviorDescriptor {
  public Break_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Break";
  }
}
