package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class ComponentIN_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public ComponentIN_BehaviorDescriptor() {
  }

  public String virtual_ggg_170812001322983771(SNode thisNode) {
    return ComponentIN_Behavior.virtual_ggg_170812001322983771(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ComponentIN";
  }
}
