package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ComponentOUT_Behavior {
  public static void init(SNode thisNode) {
  }

  public static List<SNode> virtual_getPins_4453370684997361065(SNode thisNode) {
    return SLinkOperations.getTargets(thisNode, "pins", true);

  }
}
