package ArduinoML.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

public class ComponentIN_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public ComponentIN_BehaviorDescriptor() {
  }

  public List<SNode> virtual_getPins_4453370684997361065(SNode thisNode) {
    return ComponentIN_Behavior.virtual_getPins_4453370684997361065(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ComponentIN";
  }
}
