package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class Component_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static List<SNode> call_getPins_4453370684997361065(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), thisNode, "virtual_getPins_4453370684997361065", new Object[]{});
  }

  @Deprecated
  public static List<SNode> callSuper_getPins_4453370684997361065(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "ArduinoML.structure.Component"), callerConceptFqName, "virtual_getPins_4453370684997361065", new Class[]{SNode.class}, new Object[]{});
  }
}
