package ArduinoML.behavior;

/*Generated by MPS */


public class ComponentOUT_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public ComponentOUT_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ComponentOUT";
  }
}
