package ArduinoML.behavior;

/*Generated by MPS */


public class ComponentIN_BehaviorDescriptor extends Component_BehaviorDescriptor {
  public ComponentIN_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.ComponentIN";
  }
}
