package ArduinoML.behavior;

/*Generated by MPS */


public class Decision_BehaviorDescriptor extends AbstractRule_BehaviorDescriptor {
  public Decision_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Decision";
  }
}
