package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DecisionTable_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DecisionTable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.DecisionTable";
  }
}
