package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class DigitalIN_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getType_4453370684997412076(SNode thisNode) {
    return "digital";
  }
}
