package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class DigitalOUT_BehaviorDescriptor extends PinOUT_BehaviorDescriptor {
  public DigitalOUT_BehaviorDescriptor() {
  }

  public String virtual_getType_4453370684997412076(SNode thisNode) {
    return DigitalOUT_Behavior.virtual_getType_4453370684997412076(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.DigitalOUT";
  }
}
