package ArduinoML.behavior;

/*Generated by MPS */


public class DigitalIN_BehaviorDescriptor extends PinIN_BehaviorDescriptor {
  public DigitalIN_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.DigitalIN";
  }
}
