package ArduinoML.behavior;

/*Generated by MPS */


public class DigitalOUT_BehaviorDescriptor extends PinOUT_BehaviorDescriptor {
  public DigitalOUT_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.DigitalOUT";
  }
}
