package ArduinoML.behavior;

/*Generated by MPS */


public class Exception_BehaviorDescriptor extends AbstractRule_BehaviorDescriptor {
  public Exception_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Exception";
  }
}
