package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public abstract class Pin_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Pin_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Pin";
  }

  public abstract String virtual_getType_4453370684997412076(SNode thisNode);
}
