package ArduinoML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class Pin_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_pinNumber_4453370684997791203(SNode thisNode) {
    return Integer.toString(SPropertyOperations.getInteger(thisNode, "number"));
  }

  @Deprecated
  public static String call_getType_4453370684997412076(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_getType_4453370684997412076", new Object[]{});
  }

  @Deprecated
  public static String callSuper_getType_4453370684997412076(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "ArduinoML.structure.Pin"), callerConceptFqName, "virtual_getType_4453370684997412076", new Class[]{SNode.class}, new Object[]{});
  }
}
