package ArduinoML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Pin_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Pin_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.Pin";
  }
}
