package ArduinoML.behavior;

/*Generated by MPS */


public abstract class PinIN_BehaviorDescriptor extends Pin_BehaviorDescriptor {
  public PinIN_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.PinIN";
  }
}
