package ArduinoML.behavior;

/*Generated by MPS */


public class PinOUT_BehaviorDescriptor extends Pin_BehaviorDescriptor {
  public PinOUT_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ArduinoML.structure.PinOUT";
  }
}
