package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ActionOnComponent_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.indentBuffer();
    if ((SLinkOperations.getTarget(node, "pinTarget", false) == null)) {
      Component.action_component(SLinkOperations.getTarget(node, "component", false), this);
    } else {
      Component.action_component_with_specific_pin(SLinkOperations.getTarget(node, "component", false), SLinkOperations.getTarget(node, "pinTarget", false), this);
    }
    this.append(SPropertyOperations.getString_def(node, "target", "HIGH"));
    this.append(");");
  }
}
