package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ComponentOUT_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    Component.init_component(SLinkOperations.getTargets(node, "pins", true), "OUTPUT", this);
  }
}
