package ArduinoML.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;

public class Decision_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.indentBuffer();
    this.append("if (");

    {
      Iterable<SNode> collection = SLinkOperations.getTargets(node, "conditions", true);
      final SNode lastItem = Sequence.fromIterable(collection).last();
      for (SNode item : collection) {
        appendNode(item);
        if (item != lastItem) {
          append(" && ");
        }
      }
    }

    this.append(") {");
    this.appendNewLine();
    this.increaseDepth();
    {
      Iterable<SNode> collection = SLinkOperations.getTargets(node, "actions", true);
      final SNode lastItem = Sequence.fromIterable(collection).last();
      for (SNode item : collection) {
        appendNode(item);
        if (item != lastItem) {
          append("\n");
        }
      }
    }
    this.decreaseDepth();
    this.appendNewLine();
    this.indentBuffer();
    this.append("}");
    this.append("\n");
  }
}
