package ArduinoML.textGen;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public abstract class DeclarationModules {
  public static void declareModules(List<SNode> modules, final SNodeTextGen textGen) {
    for (SNode module : ListSequence.fromList(modules)) {
      textGen.append("void ");
      textGen.append(SPropertyOperations.getString(module, "name"));
      textGen.append("\u00a0();");
      textGen.appendNewLine();
    }
  }
}
