package ArduinoML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum State {
  HIGH("HIGH", "HIGH"),
  LOW("LOW", "LOW");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<State> getConstants() {
    List<State> list = ListSequence.fromList(new LinkedList<State>());
    ListSequence.fromList(list).addElement(State.HIGH);
    ListSequence.fromList(list).addElement(State.LOW);
    return list;
  }

  public static State getDefault() {
    return State.HIGH;
  }

  public static State parseValue(String value) {
    if (value == null) {
      return State.getDefault();
    }
    if (value.equals(State.HIGH.getValueAsString())) {
      return State.HIGH;
    }
    if (value.equals(State.LOW.getValueAsString())) {
      return State.LOW;
    }
    return State.getDefault();
  }

  private String myValue;

  State(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
